# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Coley's Blog # 网站标题
subtitle: '君之所向，一往无前。' # 网站副标题
description: '' # 网站描述
keywords: # 网站关键字
author: Coley Brooks # 作者名
language: zh-CN # 网站语言
timezone: '' # 网站时区

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://blog.coley48.cn # 网址
permalink: :year/:month/:day/:title/ # 文章永久链接格式
permalink_defaults: # 永久链接中各部分的默认值
pretty_urls: # 改写 permalink 的值来美化 URL
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source # 资源文件夹，这个文件夹用来存放内容。
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # 代码文件夹，
i18n_dir: :lang # 国际化文件夹
skip_render: # 跳过指定文件的渲染。

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post # 预设布局
# auto_spacing: false # 在中文和英文之间加入空格
titlecase: false # Transform title into titlecase
external_link: # 在新标签中打开链接
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: '' # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: true # 启动 Asset 文件夹，true 创建同名文件夹，放置静态资源
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # highlight 代码高亮设置 https://hexo.io/docs/syntax-highlight#Highlight-js
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: # prismjs 代码高亮设置 https://hexo.io/docs/syntax-highlight#PrismJS
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true # Meta 标签。 值为 false 时 Hexo 不会在头部插入该标签

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime' # 当 Front Matter 中没有指定 updated 时 updated 的取值
# mtime: 使用文件的最后修改时间。这是从 Hexo 3.0.0 开始的默认行为。
# date: 使用 date 作为 updated 的值。可被用于 Git 工作流之中，因为使用 Git 管理站点时，文件的最后修改日期常常会发生改变
# empty: 直接删除 updated。使用这一选项可能会导致大部分主题和插件无法正常工作。

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 # 设置每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: # Hexo 默认会忽略隐藏文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
exclude: # Hexo 会忽略这些文件和目录
ignore: # 忽略文件或文件夹

# Deployment
# 一键部署，只上传静态文件，不适用于travis ci
## Docs: https://hexo.io/docs/one-command-deployment
# 安装依赖 npm install hexo-deployer-git --save
# deploy: # 部署部分的设置
#   type: git
#   repo: https://github.com/Coley48/coley48.github.io.git
#   branch: master


# 搜索设置
# npm install hexo-hexo-generator-searchdb -S
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# 下载 hexo next 主题
# git clone https://github.com/theme-next/hexo-theme-next themes/next
theme: next # 设置当前主题，false 禁用主题
# See: https://theme-next.org/docs/theme-settings/
theme_config: 
  # 底部
  footer:
    icon: # Icon between year and copyright info.
      name: fa fa-heart # Icon name in Font Awesome. See: https://fontawesome.com/icons
      animated: true # If you want to animate the icon, set it to true.
      color: "#fc6423" # Change the color of icon, using Hex Code.

    powered: false # Powered by Hexo & NexT
    since: 2021 # 建站时间
    copyright: Hush

  # 协议
  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: true
    language:

  # 主题
  scheme: Gemini

  # 菜单栏
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    # commonweal: /404/ || fa fa-heartbeat

  # 菜单栏设置
  menu_settings:
    icons: true
    badges: false
  # 头像
  avatar:
    # Replace the default image and set the url here.
    url: /images/avator.jpg #/images/avatar.gif
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: true
  # 社交
  social:
    GitHub: https://github.com/Coley48 || fab fa-github
    E-Mail: mailto:coley48@qq.com || fa fa-envelope
    #Weibo: https://weibo.com/yourname || fab fa-weibo
    #Google: https://plus.google.com/yourname || fab fa-google
    #Twitter: https://twitter.com/yourname || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    #YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype

  # Reward (Donate) 打赏
  # Front-matter variable (unsupport animation).
  reward_settings:
    # If true, reward will be displayed in every article by default.
    enable: false
    animation: false
    #comment: Donate comment here.

  reward:
    #wechatpay: /images/wechatpay.png
    #alipay: /images/alipay.png
    #paypal: /images/paypal.png
    #bitcoin: /images/bitcoin.png

  # 代码块
  codeblock:
    # Code Highlight theme
    # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
    # See: https://github.com/chriskempson/tomorrow-theme
    highlight_theme: normal
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Show text copy result.
      show_result: true
      # Available values: default | flat | mac
      style: mac

  # 回到顶部
  back2top:
    enable: true
    # Back to top in sidebar.
    sidebar: true
    # Scroll percent label in b2t button.
    scrollpercent: true

  # Reading progress bar 阅读进度条
  reading_progress:
    enable: true
    # Available values: top | bottom
    position: top
    color: "#37c6c0"
    height: 3px

  # `Follow me on GitHub` banner in the top-right corner.
  github_banner:
    enable: true
    permalink: https://github.com/Coley48
    title: Follow me on GitHub

  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false

  # 友链
  links:
    #Title: http://yoursite.com


## Live2D看板娘
## https://github.com/xiazeyu/live2d-widget.js
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    #模板目录，在node_modules里
    use: live2d-widget-model-hijiki
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: right
    hOffset: 0
    vOffset: -20
  mobile:
    # 在手机端显示
    show: false
    scale: 0.5
  react:
    opacity: 0.95
    opacityDefault: 0.7
    opacityOnHover: 0.2

# 文章字数统计，阅读时长估计
# npm install hexo-symbols-count-time
# https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  # 在文章头显示
  symbols: true
  time: true
  # 在文章尾部显示
  total_symbols: false
  total_time: false
  exclude_codeblock: false
  awl: 2 # 中文
  wpm: 275
  suffix: "mins."